### ISSUE TITLE
Integration fails after HA update 2025.1

### ISSUE THREAD

**Issue by Tom-ahawk** [ynsgnr/blauberg-assistant#3]
The fan is online using the phone app. 

The HA sensors are showing up as Unavailable. Does not help restarting HA. 

HA log:
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 11:04:53 (7 occurrences)
Last logged: 11:05:13


Detected that custom integration 'blauberg_fan' calls async_forward_entry_setup for integration, blauberg_fan with title: and entry_id: 01JFSSQ649FYN7K9NDDJP4H898, which is deprecated, await async_forward_entry_setups instead at custom_components/blauberg_fan/__init__.py, line 61: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/ynsgnr/blauberg-assistant/issues
Detected that custom integration 'blauberg_fan' uses `async_config_entry_first_refresh`, which is only supported when entry state is ConfigEntryState.SETUP_IN_PROGRESS, but it is in state ConfigEntryState.LOADED at custom_components/blauberg_fan/fan.py, line 39: await blauberg_coordinator.async_config_entry_first_refresh(). This will stop working in Home Assistant 2025.11, please create a bug report at https://github.com/ynsgnr/blauberg-assistant/issues
Detected that custom integration 'blauberg_fan' uses `async_config_entry_first_refresh`, which is only supported when entry state is ConfigEntryState.SETUP_IN_PROGRESS, but it is in state ConfigEntryState.LOADED at custom_components/blauberg_fan/number.py, line 36: await blauberg_coordinator.async_config_entry_first_refresh(). This will stop working in Home Assistant 2025.11, please create a bug report at https://github.com/ynsgnr/blauberg-assistant/issues
Detected that custom integration 'blauberg_fan' uses `async_config_entry_first_refresh`, which is only supported when entry state is ConfigEntryState.SETUP_IN_PROGRESS, but it is in state ConfigEntryState.LOADED at custom_components/blauberg_fan/button.py, line 33: await blauberg_coordinator.async_config_entry_first_refresh(). This will stop working in Home Assistant 2025.11, please create a bug report at https://github.com/ynsgnr/blauberg-assistant/issues
Detected that integration 'zha' calls `device_registry.async_get_or_create` referencing a non existing `via_device` ('zha', 1c:34:f1:ff:fe:ed:07:90), with device info: {'connections': {('zigbee', '00:15:8d:00:0a:f2:df:54')}, 'identifiers': {('zha', '00:15:8d:00:0a:f2:df:54')}, 'manufacturer': 'LUMI', 'model': 'lumi.sensor_motion.aq2', 'name': 'LUMI lumi.sensor_motion.aq2', 'via_device': ('zha', 1c:34:f1:ff:fe:ed:07:90)} at homeassistant/components/zha/helpers.py, line 1177: _async_add_entities(entities_to_add, update_before_add=False). This will stop working in Home Assistant 2025.12.0, please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+zha%22
```

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:234
First occurred: 11:05:12 (3 occurrences)
Last logged: 11:05:12

Detected code that calls async_forward_entry_setup for integration blauberg_fan with title: and entry_id: 01JFSSQ649FYN7K9NDDJP4H898, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue
```

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/blauberg_fan/sensor.py:16
integration: Blauberg Fan (documentation, issues)
First occurred: 11:05:12 (1 occurrences)
Last logged: 11:05:12

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2349, in async_forward_entry_setup
    result = await self._async_forward_entry_setup(entry, domain, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2380, in _async_forward_entry_setup
    await integration.async_get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1108, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1185, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1098, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1272, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1304, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/blauberg_fan/sensor.py", line 16, in <module>
    from homeassistant.const import CONF_DEVICE_ID, CONF_DEVICES, PERCENTAGE, TEMP_CELSIUS
ImportError: cannot import name 'TEMP_CELSIUS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

**Comment by Tom-ahawk** [comment]
Thanks for maintaing this integration ; D

**Comment by lionkingQ12** [comment]
Hello, I installed the integration, but it works only once, most of the time it loses connection with the device. I have two types of devices, one of them doesn't work at all, but the integration sees them. 
Not work
https://ventilation-system.com/series/breezy/
Work 
https://ventilation-system.com/series/ifan/

<img width="1189" alt="Image" src="https://github.com/user-attachments/assets/b151cc45-a080-490e-a1ef-77144fa9084c" />

**Comment by lionkingQ12** [comment]
Logger : homeassistant.helpers.frame
Source : helpers/frame.py:234 First occurred : 21:22:33 ( 4 occurrences ) Last recorded : 21:22:33



Detected code that calls async_forward_entry_setup for integration blauberg_fan with title: and entry_id: 01JK41D4J8ST9RNBTKH4NDCMQJ, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue
